version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD" , "pg_isready"]
    ports:
      - "5432:5432"
    networks:
      - chat-network

  migrate:
    image: migrate/migrate:latest
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    volumes:
      - ./db/migrations:/migrations
    command:
      ["-path", "/migrations" , "-database" , "postgres://postgres:0@postgres:5432/postgres?sslmode=disable" , "up"]
    networks:
      - chat-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - chat-network

  api-gateway:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-api-gateway
    image: chat-app-api-gateway
    environment:
      APP_NAME: "api-gateway service"
      GRPC_AUTH_HOST: auth
      GRPC_CHAT_HOST: chat
      GRPC_USER_HOST: user
    ports:
      - "5000:5000"
    depends_on:
      - auth
      - chat
      - user
    networks:
      - chat-network

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./docker/Dockerfile-auth
    image: chat-app-auth
    environment:
      APP_NAME: "auth service"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 0
      DB_NAME: postgres
      REDIS_HOST: redis
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - chat-network

  chat:
    container_name: chat
    build:
      context: .
      dockerfile: ./docker/Dockerfile-chat
    image: chat-app-chat
    environment:
      APP_NAME: "chat service"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 0
      DB_NAME:
      REDIS_HOST: redis
    ports:
      - "50052:50052"
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - chat-network

  user:
    container_name: user
    build:
      context: .
      dockerfile: ./docker/Dockerfile-user
    image: chat-app-user
    environment:
      APP_NAME: "user service"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 0
      DB_NAME: postgres
      REDIS_HOST: redis
    ports:
      - "50053:50053"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - chat-network


networks:
  chat-network: