# Step 1: Modules caching
FROM golang:1.24-alpine3.20 as  modules
COPY go.mod go.sum /modules/
WORKDIR /modules
RUN go mod download

# Step 2: Builder
FROM golang:1.24-alpine3.20 as builder
COPY --from=modules /go/pkg /go/pkg
COPY . /app
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
     go build -tags migrate -o /bin/app ./cmd/auth

# Step 3: Final
FROM scratch

EXPOSE 50051

COPY --from=builder /app/cmd/auth/config/config.yml /
COPY --from=builder /app/db/migrations /db/migrations
COPY --from=builder /bin/app /app
CMD ["/app"]