// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatChat struct {
	ID        pgtype.UUID      `json:"id"`
	Type      string           `json:"type"`
	Name      pgtype.Text      `json:"name"`
	CreatorID pgtype.UUID      `json:"creator_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ChatChatMember struct {
	ID       pgtype.UUID      `json:"id"`
	ChatID   pgtype.UUID      `json:"chat_id"`
	UserID   pgtype.UUID      `json:"user_id"`
	Role     string           `json:"role"`
	Status   string           `json:"status"`
	JoinedAt pgtype.Timestamp `json:"joined_at"`
}

type ChatMessage struct {
	ID        pgtype.UUID      `json:"id"`
	ChatID    pgtype.UUID      `json:"chat_id"`
	SenderID  pgtype.UUID      `json:"sender_id"`
	Content   pgtype.Text      `json:"content"`
	Type      string           `json:"type"`
	MediaUrl  pgtype.Text      `json:"media_url"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ChatMessageStatus struct {
	MessageID pgtype.UUID      `json:"message_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Status    string           `json:"status"`
	ReadAt    pgtype.Timestamp `json:"read_at"`
}
