app:
  name: 'chat-service'
  version : '1.0.0'

http:
  host: '0.0.0.0'
  port: 5002

database:
  postgres:
    host: localhost
    port: 5432
    user: postgres
    password: 0
    database: chat_app
    sslmode: disable
  redis:
    host: localhost
    port: 6379
    password: ""
    database: 1